export const SEARCH_YOUTUBE_VIDEOS = 'SEARCH_YOUTUBE_VIDEOS';
export const FETCH_VIDEO_FULFILLED = 'FETCH_VIDEO_FULFILLED';
export const SEARCH_NEXT_YOUTUBE_VIDEOS = 'SEARCH_NEXT_YOUTUBE_VIDEOS';
export const FETCH_NEXT_VIDEO_FULFILLED = 'FETCH_NEXT_VIDEO_FULFILLED';
export const FETCH_FAIL = 'FETCH_FAIL';
export const CHANGE_PAGE = 'CHANGE_PAGE';